### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ssli23** [ChelseaM-C/MICCAI2022-Heatmap-Lesion-Detection#1]
Would you be comfortable sharing a small part of the dataset? In that case, I can follow your data.

**Comment by ChelseaM-C** [comment]
> Would you be comfortable sharing a small part of the dataset? In that case, I can follow your data.

Hi, unfortunately the data is from a proprietary dataset that I am unable to share. You can create your own dataset that should work if you follow the formatting guidelines in the README though!
